version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USER=ewm-user
      - SPRING_DATASOURCE_PASSWORD=ewm-password


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_USER=ewm-user
        - POSTGRES_PASSWORD=ewm-password
        - POSTGRES_DB=ewm-stats

  ewm-service:
    build: main
    image: main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=ewm-user
      - SPRING_DATASOURCE_PASSWORD=ewm-password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-postgres-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=ewm-password